### ISSUE TITLE
Pokemon Go Forced Close

### ISSUE THREAD

**Issue by PhantomAssassin12** [ngoquang2708/android_device_samsung_vivalto3gvn#67]
@ngoquang2708 
The pokemon Go is closing after I login without any box that says pokemon has force closed.
[LogFile Here.](https://github.com/ngoquang2708/android_device_samsung_vivalto3gvn/files/405241/logfile.txt)

**Comment by ngoquang2708** [comment]
Our device doesn't meet the requirement to able to run PG.

**Comment by diepquynh** [comment]
Pokemon Go is actually can be played with our phone, but stock and CM12.1 only (I have seen that in my FB group)

**Comment by PhantomAssassin12** [comment]
I Flash the stock but still no luck.

**Comment by bagaskara815** [comment]
im using GLtools in CM11 but still Lag and then crash

**Comment by diepquynh** [comment]
@bagaskara815 
GLtools is just a placebo software for our device. Since our GPU was just single-core with a very low speed (312MHz), you can't except any improvements with GLtools, because it just do some hacks with OpenGL rendering module (libGLESv2 and libGLESv3), not making "magics" with our phone

**Comment by bagaskara815** [comment]
@koquantam thanks for you explanation

**Comment by ngoquang2708** [comment]
So this issue is not related to this ROM but the hardware it self, confirmed with @PhantomAssassin12 report.
