### ISSUE TITLE
No ADB

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_device_samsung_vivalto3gvn#93]
First clue:
```
<31>[   14.721776] C0 [    logd.daemon, 600] logd: logd.daemon: failed to set AID_SYSTEM AID_PACKAGE_INFO groups
<31>[   14.721946] C0 [           logd, 592] logd: failed to set CAP_SETGID, CAP_SYSLOG or CAP_AUDIT_CONTROL (1)
<14>[   14.726895] C0 [           init, 1] init: Sending signal 9 to service 'logd' (pid 592) process group...
```

**Comment by ngoquang2708** [comment]
We have to enable it in the GUI or set prop ```persist.sys.usb.config=mtp,adb``` either in build time or in runtime.

**Comment by diepquynh** [comment]
I have another option: Hack up adbd source in system/core
Look at daemon/main.cpp, comment out line 161 and 163, force return true on line 93
https://github.com/LineageOS/android_system_core/blob/lineage-15.1/adb/daemon/main.cpp#L161
https://github.com/LineageOS/android_system_core/blob/lineage-15.1/adb/daemon/main.cpp#L93

The culprit is somehow `PRODUCT_DEFAULT_PROPERTY_OVERRIDES` doesn't override our adb props, or we don't know how it actually works

**Comment by ngoquang2708** [comment]
I built eng variant and set prop ```persist.sys.usb.config=mtp,adb``` in ```system.prop```. My ADB can work with that.
